### ISSUE TITLE
Does not work on Ubuntu 12.04

### ISSUE THREAD

**Issue by ghost** [wix/mysqler#1]
npacking mysql-server (from .../mysql-server_5.5.44-0ubuntu0.12.04.1_all.deb) ...
    Processing triggers for man-db ...
    Processing triggers for ureadahead ...
    Setting up libnet-daemon-perl (0.48-1) ...
    Setting up libplrpc-perl (0.2020-2) ...
    Setting up libdbi-perl (1.616-1build2) ...
    Setting up libdbd-mysql-perl (4.020-1build2) ...
    Setting up mysql-client-core-5.5 (5.5.44-0ubuntu0.12.04.1) ...
    Setting up libterm-readkey-perl (2.30-4build3) ...
    Setting up mysql-client-5.5 (5.5.44-0ubuntu0.12.04.1) ...
    Setting up mysql-server-core-5.5 (5.5.44-0ubuntu0.12.04.1) ...
    Setting up mysql-server-5.5 (5.5.44-0ubuntu0.12.04.1) ...
    Setting up libhtml-template-perl (2.10-1) ...
    STDERR: invoke-rc.d: unknown initscript, /etc/init.d/mysql not found.
    invoke-rc.d: unknown initscript, /etc/init.d/mysql not found.
    dpkg: error processing mysql-server-5.5 (--configure):
     subprocess installed post-installation script returned error exit status 100
    dpkg: dependency problems prevent configuration of mysql-server:
     mysql-server depends on mysql-server-5.5; however:
      Package mysql-server-5.5 is not configured yet.
    dpkg: error processing mysql-server (--configure):
     dependency problems - leaving unconfigured
    No apport report written because the error message indicates its a followup error from a previous failure.
    Errors were encountered while processing:
     mysql-server-5.5
     mysql-server
    E: Sub-process /usr/bin/dpkg returned an error code (1)
    ---- End output of apt-get -q -y --force-yes -o Dpkg::Options="--no-triggers" install mysql-server=5.5.44-0ubuntu0.12.04.1 ----
    Ran apt-get -q -y --force-yes -o Dpkg::Options="--no-triggers" install mysql-server=5.5.44-0ubuntu0.12.04.1 returned 100

**Comment by tata2000** [comment]
Hi,

It was tested on debian only as it says in the description. 
What is happening here - is that we remove the /etc/init.d/mysql file in order to revent it to shutdown multiple instances later on (the original file is stopping all the instances of mysql 

setting this attribute to false will install the default init file.
['mysqler'][:mysql_server_remove_default_init_script] = false

please let me know if it helpped.

**Comment by ghost** [comment]
Hi, nah it's all good, Ubuntu is Debian. But no matter, I wrote a
light-weight script to replace Chef about 3 months ago,  works on the
current, and last 2 versions of Ubuntu  so no worries.
Thanx for getting back to me.

Best regards,
Alwyn.

On Sat, Oct 17, 2015 at 7:00 PM, Tatyana Arenburg notifications@github.com
wrote:

> Hi,
> 
> It was tested on debian only as it says in the description.
> What is happening here - is that we remove the /etc/init.d/mysql file in
> order to revent it to shutdown multiple instances later on (the original
> file is stopping all the instances of mysql
> 
> setting this attribute to false will install the default init file.
> ['mysqler'][:mysql_server_remove_default_init_script] = false
> 
> please let me know if it helpped.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wix/mysqler/issues/1#issuecomment-148934146.

## 

http://alwyndippenaar.com

**Comment by tata2000** [comment]
Hi Alwyn,

I just used it several days ago on debian 7.8 (with removal of the init script) and didn't encounter any problem.
The package provided from the MySQL repository might be different for Debian and Ubuntu.
Unfortunately on Debian it does not require the init file to start the mysql and on Ubuntu  - it does require it (as we see from the error message). 

Thanks for submitting this issue. I'll add this to README.

Best regards,
Tatyana.
